-- Zettel database schema — run once against your Neon PostgreSQL instance
-- Matches the EF Core migration history exactly.

CREATE EXTENSION IF NOT EXISTS vector;

-- ── Notes ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Notes" (
  "Id"              varchar(21)  PRIMARY KEY,
  "Title"           text         NOT NULL,
  "Content"         text         NOT NULL,
  "CreatedAt"       timestamptz  NOT NULL DEFAULT now(),
  "UpdatedAt"       timestamptz  NOT NULL DEFAULT now(),
  "Status"          varchar(20)  NOT NULL DEFAULT 'Permanent',
  "Source"          varchar(20),
  "EnrichmentJson"  text,
  "EnrichStatus"    varchar(20)  NOT NULL DEFAULT 'None',
  "EnrichRetryCount" integer     NOT NULL DEFAULT 0,
  "Embedding"       real[],
  "EmbedStatus"     varchar(20)  NOT NULL DEFAULT 'Pending',
  "EmbedRetryCount" integer      NOT NULL DEFAULT 0,
  "EmbedError"      text,
  "EmbedUpdatedAt"  timestamptz,
  "EmbeddingModel"  varchar(100),
  "NoteType"        varchar(20)  NOT NULL DEFAULT 'Regular',
  "SourceAuthor"    text,
  "SourceTitle"     text,
  "SourceUrl"       text,
  "SourceYear"      integer,
  "SourceType"      varchar(20)
);

CREATE TABLE IF NOT EXISTS "NoteTags" (
  "NoteId"  varchar(21) NOT NULL REFERENCES "Notes"("Id") ON DELETE CASCADE,
  "Tag"     text        NOT NULL,
  PRIMARY KEY ("NoteId", "Tag")
);

CREATE TABLE IF NOT EXISTS "NoteVersions" (
  "Id"       integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NoteId"   varchar(21) NOT NULL REFERENCES "Notes"("Id") ON DELETE CASCADE,
  "Title"    text        NOT NULL,
  "Content"  text        NOT NULL,
  "Tags"     text,
  "SavedAt"  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notes_status     ON "Notes"("Status");
CREATE INDEX IF NOT EXISTS idx_notes_notetype   ON "Notes"("NoteType");
CREATE INDEX IF NOT EXISTS idx_notes_created_at ON "Notes"("CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS idx_notetags_tag     ON "NoteTags"("Tag");
CREATE INDEX IF NOT EXISTS "IX_NoteVersions_NoteId" ON "NoteVersions"("NoteId");

CREATE INDEX IF NOT EXISTS idx_notes_embed_status ON "Notes"("EmbedStatus")
  WHERE "EmbedStatus" IN ('Pending', 'Failed', 'Stale');

CREATE INDEX IF NOT EXISTS idx_notes_enrich_status ON "Notes"("EnrichStatus")
  WHERE "EnrichStatus" IN ('Pending', 'Failed');

CREATE INDEX IF NOT EXISTS idx_notes_fulltext ON "Notes"
  USING GIN (to_tsvector('english', "Title" || ' ' || "Content"));

-- ── Content generation ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "ContentGenerations" (
  "Id"             varchar(21)  PRIMARY KEY,
  "SeedNoteId"     varchar(21)  NOT NULL,
  "ClusterNoteIds" jsonb        NOT NULL DEFAULT '[]',
  "TopicSummary"   text         NOT NULL,
  "TopicEmbedding" real[],
  "Status"         varchar(20)  NOT NULL DEFAULT 'Pending',
  "GeneratedAt"    timestamptz  NOT NULL DEFAULT now(),
  "ReviewedAt"     timestamptz
);

CREATE TABLE IF NOT EXISTS "ContentPieces" (
  "Id"            varchar(21)  PRIMARY KEY,
  "GenerationId"  varchar(21)  NOT NULL REFERENCES "ContentGenerations"("Id") ON DELETE CASCADE,
  "Medium"        varchar(20)  NOT NULL,
  "Body"          text         NOT NULL,
  "Description"   text,
  "GeneratedTags" jsonb        NOT NULL DEFAULT '[]',
  "Status"        varchar(20)  NOT NULL DEFAULT 'Draft',
  "CreatedAt"     timestamptz  NOT NULL DEFAULT now(),
  "ReviewedAt"    timestamptz
);

CREATE INDEX IF NOT EXISTS "IX_ContentPieces_GenerationId" ON "ContentPieces"("GenerationId");
CREATE INDEX IF NOT EXISTS "IX_ContentPieces_Status"       ON "ContentPieces"("Status");

CREATE TABLE IF NOT EXISTS "UsedSeedNotes" (
  "NoteId"  varchar(21)  PRIMARY KEY,
  "UsedAt"  timestamptz  NOT NULL DEFAULT now()
);

-- ── Voice ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "VoiceExamples" (
  "Id"        varchar(21)  PRIMARY KEY,
  "Medium"    varchar(20)  NOT NULL,
  "Content"   text         NOT NULL,
  "CreatedAt" timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_VoiceExamples_Medium" ON "VoiceExamples"("Medium");

CREATE TABLE IF NOT EXISTS "VoiceConfigs" (
  "Id"                   varchar(21)  PRIMARY KEY,
  "Medium"               varchar(20)  NOT NULL,
  "ToneDescription"      text,
  "AudienceDescription"  text,
  "UpdatedAt"            timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_VoiceConfigs_Medium" ON "VoiceConfigs"("Medium");

-- ── Research ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "ResearchAgendas" (
  "Id"                  varchar(21)  PRIMARY KEY,
  "TriggeredFromNoteId" varchar(21),
  "Status"              varchar(20)  NOT NULL DEFAULT 'Pending',
  "CreatedAt"           timestamptz  NOT NULL DEFAULT now(),
  "ApprovedAt"          timestamptz
);

CREATE TABLE IF NOT EXISTS "ResearchTasks" (
  "Id"               varchar(21)  PRIMARY KEY,
  "AgendaId"         varchar(21)  NOT NULL REFERENCES "ResearchAgendas"("Id") ON DELETE CASCADE,
  "Query"            text         NOT NULL,
  "SourceType"       varchar(20)  NOT NULL,
  "Motivation"       text         NOT NULL,
  "MotivationNoteId" varchar(21),
  "Status"           varchar(20)  NOT NULL DEFAULT 'Pending',
  "BlockedAt"        timestamptz
);

CREATE INDEX IF NOT EXISTS "IX_ResearchTasks_AgendaId" ON "ResearchTasks"("AgendaId");

CREATE TABLE IF NOT EXISTS "ResearchFindings" (
  "Id"                    varchar(21)   PRIMARY KEY,
  "TaskId"                varchar(21)   NOT NULL REFERENCES "ResearchTasks"("Id"),
  "Title"                 text          NOT NULL,
  "Synthesis"             text          NOT NULL,
  "SourceUrl"             text          NOT NULL,
  "SourceType"            varchar(20)   NOT NULL,
  "SimilarNoteIds"        jsonb         NOT NULL DEFAULT '[]',
  "DuplicateSimilarity"   float8,
  "Status"                varchar(20)   NOT NULL DEFAULT 'Pending',
  "AcceptedFleetingNoteId" varchar(21),
  "CreatedAt"             timestamptz   NOT NULL DEFAULT now(),
  "ReviewedAt"            timestamptz
);

CREATE INDEX IF NOT EXISTS "IX_ResearchFindings_TaskId"        ON "ResearchFindings"("TaskId");
CREATE INDEX IF NOT EXISTS "IX_ResearchFindings_Status_Created" ON "ResearchFindings"("Status", "CreatedAt" DESC);

-- HNSW index for vector search (run after loading data, adjust dimensions to match your model)
-- Example for text-embedding-3-large (3072 dims):
-- CREATE INDEX IF NOT EXISTS idx_notes_embedding_hnsw
--   ON "Notes" USING hnsw (("Embedding"::vector(3072)) vector_cosine_ops)
--   WHERE "Embedding" IS NOT NULL;
